=== NORTHREND05/lenguaje-de-marcas/ejercicio6/gasolinera.dtd
<!ELEMENT gasolinera (tanques, tanques, tanques, tanques, clientes, ventas)>

<!ELEMENT tanques (litros_entrada, litros_salida, fecha)>
<!ATTLIST tanques tipo_combustible CDATA #FIXED "gasolina95">

<!ELEMENT litros_entrada (#PCDATA)>
<!ELEMENT litros_salida (#PCDATA)>
<!ATTLIST litros_salida id ID #REQUIRED>

<!ELEMENT fecha (#PCDATA)>

<!ELEMENT clientes (nombre, apellidos, DNI, telefono?, email?)>
<!ATTLIST clientes id ID #REQUIRED pais CDATA #FIXED "ES">

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT ventas (#PCDATA)>
<!ATTLIST ventas operacion IDREF #REQUIRED cliente IDREF #REQUIRED>

=== NORTHREND05/lenguaje-de-marcas/ejercicio6/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gasolinera SYSTEM "gasolinera.dtd">

<gasolinera>
    <tanques>
        <litros_entrada></litros_entrada>
        <litros_salida id="acb"></litros_salida>
        <fecha></fecha>
    </tanques>
    <tanques>
        <litros_entrada></litros_entrada>
        <litros_salida id="bca"></litros_salida>
        <fecha></fecha>
    </tanques>
    <tanques>
        <litros_entrada></litros_entrada>
        <litros_salida id="cba"></litros_salida>
        <fecha></fecha>
    </tanques>
    <tanques>
        <litros_entrada></litros_entrada>
        <litros_salida id="abc"></litros_salida>
        <fecha></fecha>
    </tanques>
    <clientes id="cliente1">
        <nombre></nombre>
        <apellidos></apellidos>
        <DNI></DNI>
    </clientes>
    <ventas operacion="acb" cliente="cliente1"></ventas>
</gasolinera>
