=== NORTHREND05/lenguaje-de-marcas/ejercicio1/inventario.dtd
<!ELEMENT inventario (lapiz | cuaderno | boligrafo)*>
<!ELEMENT lapiz (dureza?)>
<!ELEMENT cuaderno (numhojas, estilo)>
<!ELEMENT boligrafo (precio, color?)>
<!ELEMENT dureza (#PCDATA)>
<!ELEMENT numhojas (#PCDATA)>
<!ELEMENT estilo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT color (#PCDATA)>

=== NORTHREND05/lenguaje-de-marcas/ejercicio1/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventario SYSTEM "inventario.dtd">
<inventario>
    <lapiz>
        <dureza></dureza>
    </lapiz>
    <boligrafo>
        <precio></precio>
        <color></color>
    </boligrafo>
    <cuaderno>
        <numhojas></numhojas>
        <estilo></estilo>
    </cuaderno>
</inventario>
