=== NORTHREND05/lenguaje-de-marcas/ejercicio3/listacursos.dtd
<!ELEMENT listacursos (cursos+)>
<!ELEMENT cursos (alumnos+)>
<!ELEMENT alumnos (dni, nombre, apellido, segundo_apellido?, lista_asignaturas)>
<!ELEMENT lista_asignaturas (asignatura+)>
<!ELEMENT asignatura (nombre, profesor)>
<!ELEMENT profesor (NRP, nombre, apellido, segundo_apellido?)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT NRP (#PCDATA)>
<!ATTLIST asignatura codigo ID #REQUIRED>

=== NORTHREND05/lenguaje-de-marcas/ejercicio3/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacursos SYSTEM "listacursos.dtd">

<listacursos>
    <cursos>
        <alumnos>
            <dni>20202020T</dni>
            <nombre>Manolo</nombre>
            <apellido>Gimenez</apellido>
            <lista_asignaturas>
                <asignatura codigo="C1">
                    <nombre>LMSGI</nombre>
                    <profesor>
                        <NRP>2020020</NRP>
                        <nombre>Pepe</nombre>
                        <apellido>Padre</apellido>
                    </profesor>
                </asignatura>
            </lista_asignaturas>
        </alumnos>
    </cursos>
</listacursos>
